//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NabuPdfGenerator.Payment {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ofd.aisa.ru/payment", ConfigurationName="Payment.PaymentPort")]
    public interface PaymentPort {
        
        // CODEGEN: Контракт генерации сообщений с операцией UpdateInvoice не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NabuPdfGenerator.Payment.UpdateInvoiceResponse1 UpdateInvoice(NabuPdfGenerator.Payment.UpdateInvoiceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NabuPdfGenerator.Payment.UpdateInvoiceResponse1> UpdateInvoiceAsync(NabuPdfGenerator.Payment.UpdateInvoiceRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией UpdateKKTPeriod не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NabuPdfGenerator.Payment.UpdateKKTPeriodResponse1 UpdateKKTPeriod(NabuPdfGenerator.Payment.UpdateKKTPeriodRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NabuPdfGenerator.Payment.UpdateKKTPeriodResponse1> UpdateKKTPeriodAsync(NabuPdfGenerator.Payment.UpdateKKTPeriodRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией KKTStatus не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NabuPdfGenerator.Payment.KKTStatusResponse1 KKTStatus(NabuPdfGenerator.Payment.KKTStatusRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NabuPdfGenerator.Payment.KKTStatusResponse1> KKTStatusAsync(NabuPdfGenerator.Payment.KKTStatusRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией payment не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NabuPdfGenerator.Payment.paymentResponse1 payment(NabuPdfGenerator.Payment.paymentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NabuPdfGenerator.Payment.paymentResponse1> paymentAsync(NabuPdfGenerator.Payment.paymentRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией afterPaymentAccount не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NabuPdfGenerator.Payment.afterPaymentAccountResponse1 afterPaymentAccount(NabuPdfGenerator.Payment.afterPaymentAccountRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NabuPdfGenerator.Payment.afterPaymentAccountResponse1> afterPaymentAccountAsync(NabuPdfGenerator.Payment.afterPaymentAccountRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией document не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NabuPdfGenerator.Payment.documentResponse1 document(NabuPdfGenerator.Payment.documentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NabuPdfGenerator.Payment.documentResponse1> documentAsync(NabuPdfGenerator.Payment.documentRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class UpdateInvoiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int request_idField;
        
        private string new_dateField;
        
        private long new_amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int request_id {
            get {
                return this.request_idField;
            }
            set {
                this.request_idField = value;
                this.RaisePropertyChanged("request_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string new_date {
            get {
                return this.new_dateField;
            }
            set {
                this.new_dateField = value;
                this.RaisePropertyChanged("new_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long new_amount {
            get {
                return this.new_amountField;
            }
            set {
                this.new_amountField = value;
                this.RaisePropertyChanged("new_amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class UpdateInvoiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateInvoiceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ofd.aisa.ru/payment", Order=0)]
        public NabuPdfGenerator.Payment.UpdateInvoiceRequest UpdateInvoiceRequest;
        
        public UpdateInvoiceRequest1() {
        }
        
        public UpdateInvoiceRequest1(NabuPdfGenerator.Payment.UpdateInvoiceRequest UpdateInvoiceRequest) {
            this.UpdateInvoiceRequest = UpdateInvoiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateInvoiceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ofd.aisa.ru/payment", Order=0)]
        public NabuPdfGenerator.Payment.UpdateInvoiceResponse UpdateInvoiceResponse;
        
        public UpdateInvoiceResponse1() {
        }
        
        public UpdateInvoiceResponse1(NabuPdfGenerator.Payment.UpdateInvoiceResponse UpdateInvoiceResponse) {
            this.UpdateInvoiceResponse = UpdateInvoiceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class UpdateKKTPeriodRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int request_idField;
        
        private string rnmField;
        
        private string start_dateField;
        
        private string end_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int request_id {
            get {
                return this.request_idField;
            }
            set {
                this.request_idField = value;
                this.RaisePropertyChanged("request_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string rnm {
            get {
                return this.rnmField;
            }
            set {
                this.rnmField = value;
                this.RaisePropertyChanged("rnm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string start_date {
            get {
                return this.start_dateField;
            }
            set {
                this.start_dateField = value;
                this.RaisePropertyChanged("start_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string end_date {
            get {
                return this.end_dateField;
            }
            set {
                this.end_dateField = value;
                this.RaisePropertyChanged("end_date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class UpdateKKTPeriodResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateKKTPeriodRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ofd.aisa.ru/payment", Order=0)]
        public NabuPdfGenerator.Payment.UpdateKKTPeriodRequest UpdateKKTPeriodRequest;
        
        public UpdateKKTPeriodRequest1() {
        }
        
        public UpdateKKTPeriodRequest1(NabuPdfGenerator.Payment.UpdateKKTPeriodRequest UpdateKKTPeriodRequest) {
            this.UpdateKKTPeriodRequest = UpdateKKTPeriodRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateKKTPeriodResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ofd.aisa.ru/payment", Order=0)]
        public NabuPdfGenerator.Payment.UpdateKKTPeriodResponse UpdateKKTPeriodResponse;
        
        public UpdateKKTPeriodResponse1() {
        }
        
        public UpdateKKTPeriodResponse1(NabuPdfGenerator.Payment.UpdateKKTPeriodResponse UpdateKKTPeriodResponse) {
            this.UpdateKKTPeriodResponse = UpdateKKTPeriodResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class KKTStatusRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rnmField;
        
        private string deactivation_dateField;
        
        private int activationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rnm {
            get {
                return this.rnmField;
            }
            set {
                this.rnmField = value;
                this.RaisePropertyChanged("rnm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string deactivation_date {
            get {
                return this.deactivation_dateField;
            }
            set {
                this.deactivation_dateField = value;
                this.RaisePropertyChanged("deactivation_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int activation {
            get {
                return this.activationField;
            }
            set {
                this.activationField = value;
                this.RaisePropertyChanged("activation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class KKTStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KKTStatusRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ofd.aisa.ru/payment", Order=0)]
        public NabuPdfGenerator.Payment.KKTStatusRequest KKTStatusRequest;
        
        public KKTStatusRequest1() {
        }
        
        public KKTStatusRequest1(NabuPdfGenerator.Payment.KKTStatusRequest KKTStatusRequest) {
            this.KKTStatusRequest = KKTStatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KKTStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ofd.aisa.ru/payment", Order=0)]
        public NabuPdfGenerator.Payment.KKTStatusResponse KKTStatusResponse;
        
        public KKTStatusResponse1() {
        }
        
        public KKTStatusResponse1(NabuPdfGenerator.Payment.KKTStatusResponse KKTStatusResponse) {
            this.KKTStatusResponse = KKTStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class paymentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberField;
        
        private string datePaymentField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string datePayment {
            get {
                return this.datePaymentField;
            }
            set {
                this.datePaymentField = value;
                this.RaisePropertyChanged("datePayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class paymentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ofd.aisa.ru/payment", Order=0)]
        public NabuPdfGenerator.Payment.paymentRequest paymentRequest;
        
        public paymentRequest1() {
        }
        
        public paymentRequest1(NabuPdfGenerator.Payment.paymentRequest paymentRequest) {
            this.paymentRequest = paymentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ofd.aisa.ru/payment", Order=0)]
        public NabuPdfGenerator.Payment.paymentResponse paymentResponse;
        
        public paymentResponse1() {
        }
        
        public paymentResponse1(NabuPdfGenerator.Payment.paymentResponse paymentResponse) {
            this.paymentResponse = paymentResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class afterPaymentAccountRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberAccountField;
        
        private System.DateTime createDateField;
        
        private string nameClientField;
        
        private string innField;
        
        private string kppField;
        
        private string addressField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private string phoneField;
        
        private string salesNumberField;
        
        private long amountField;
        
        private long ndsField;
        
        private long totalAmountField;
        
        private int countField;
        
        private long sumWordsField;
        
        private afterPaymentAccountRequestItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numberAccount {
            get {
                return this.numberAccountField;
            }
            set {
                this.numberAccountField = value;
                this.RaisePropertyChanged("numberAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("createDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nameClient {
            get {
                return this.nameClientField;
            }
            set {
                this.nameClientField = value;
                this.RaisePropertyChanged("nameClient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
                this.RaisePropertyChanged("inn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
                this.RaisePropertyChanged("kpp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string salesNumber {
            get {
                return this.salesNumberField;
            }
            set {
                this.salesNumberField = value;
                this.RaisePropertyChanged("salesNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long nds {
            get {
                return this.ndsField;
            }
            set {
                this.ndsField = value;
                this.RaisePropertyChanged("nds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public long totalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
                this.RaisePropertyChanged("totalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public long sumWords {
            get {
                return this.sumWordsField;
            }
            set {
                this.sumWordsField = value;
                this.RaisePropertyChanged("sumWords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Order=15)]
        public afterPaymentAccountRequestItem[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class afterPaymentAccountRequestItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameServiceField;
        
        private int countField;
        
        private long sumField;
        
        private long priceField;
        
        private string[] rnmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nameService {
            get {
                return this.nameServiceField;
            }
            set {
                this.nameServiceField = value;
                this.RaisePropertyChanged("nameService");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long sum {
            get {
                return this.sumField;
            }
            set {
                this.sumField = value;
                this.RaisePropertyChanged("sum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rnm", Order=4)]
        public string[] rnm {
            get {
                return this.rnmField;
            }
            set {
                this.rnmField = value;
                this.RaisePropertyChanged("rnm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class afterPaymentAccountResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("document");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class afterPaymentAccountRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ofd.aisa.ru/payment", Order=0)]
        public NabuPdfGenerator.Payment.afterPaymentAccountRequest afterPaymentAccountRequest;
        
        public afterPaymentAccountRequest1() {
        }
        
        public afterPaymentAccountRequest1(NabuPdfGenerator.Payment.afterPaymentAccountRequest afterPaymentAccountRequest) {
            this.afterPaymentAccountRequest = afterPaymentAccountRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class afterPaymentAccountResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ofd.aisa.ru/payment", Order=0)]
        public NabuPdfGenerator.Payment.afterPaymentAccountResponse afterPaymentAccountResponse;
        
        public afterPaymentAccountResponse1() {
        }
        
        public afterPaymentAccountResponse1(NabuPdfGenerator.Payment.afterPaymentAccountResponse afterPaymentAccountResponse) {
            this.afterPaymentAccountResponse = afterPaymentAccountResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class documentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private documentRequestType typeField;
        
        private string dateField;
        
        private string innField;
        
        private string numberField;
        
        private documentRequestAction actionField;
        
        private string documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public documentRequestType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
                this.RaisePropertyChanged("inn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public documentRequestAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("document");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public enum documentRequestType {
        
        /// <remarks/>
        act,
        
        /// <remarks/>
        sf,
        
        /// <remarks/>
        upd,
        
        /// <remarks/>
        verification,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public enum documentRequestAction {
        
        /// <remarks/>
        insert,
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ofd.aisa.ru/payment")]
    public partial class documentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class documentRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ofd.aisa.ru/payment", Order=0)]
        public NabuPdfGenerator.Payment.documentRequest documentRequest;
        
        public documentRequest1() {
        }
        
        public documentRequest1(NabuPdfGenerator.Payment.documentRequest documentRequest) {
            this.documentRequest = documentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class documentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ofd.aisa.ru/payment", Order=0)]
        public NabuPdfGenerator.Payment.documentResponse documentResponse;
        
        public documentResponse1() {
        }
        
        public documentResponse1(NabuPdfGenerator.Payment.documentResponse documentResponse) {
            this.documentResponse = documentResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentPortChannel : NabuPdfGenerator.Payment.PaymentPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentPortClient : System.ServiceModel.ClientBase<NabuPdfGenerator.Payment.PaymentPort>, NabuPdfGenerator.Payment.PaymentPort {
        
        public PaymentPortClient() {
        }
        
        public PaymentPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NabuPdfGenerator.Payment.UpdateInvoiceResponse1 NabuPdfGenerator.Payment.PaymentPort.UpdateInvoice(NabuPdfGenerator.Payment.UpdateInvoiceRequest1 request) {
            return base.Channel.UpdateInvoice(request);
        }
        
        public NabuPdfGenerator.Payment.UpdateInvoiceResponse UpdateInvoice(NabuPdfGenerator.Payment.UpdateInvoiceRequest UpdateInvoiceRequest) {
            NabuPdfGenerator.Payment.UpdateInvoiceRequest1 inValue = new NabuPdfGenerator.Payment.UpdateInvoiceRequest1();
            inValue.UpdateInvoiceRequest = UpdateInvoiceRequest;
            NabuPdfGenerator.Payment.UpdateInvoiceResponse1 retVal = ((NabuPdfGenerator.Payment.PaymentPort)(this)).UpdateInvoice(inValue);
            return retVal.UpdateInvoiceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NabuPdfGenerator.Payment.UpdateInvoiceResponse1> NabuPdfGenerator.Payment.PaymentPort.UpdateInvoiceAsync(NabuPdfGenerator.Payment.UpdateInvoiceRequest1 request) {
            return base.Channel.UpdateInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<NabuPdfGenerator.Payment.UpdateInvoiceResponse1> UpdateInvoiceAsync(NabuPdfGenerator.Payment.UpdateInvoiceRequest UpdateInvoiceRequest) {
            NabuPdfGenerator.Payment.UpdateInvoiceRequest1 inValue = new NabuPdfGenerator.Payment.UpdateInvoiceRequest1();
            inValue.UpdateInvoiceRequest = UpdateInvoiceRequest;
            return ((NabuPdfGenerator.Payment.PaymentPort)(this)).UpdateInvoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NabuPdfGenerator.Payment.UpdateKKTPeriodResponse1 NabuPdfGenerator.Payment.PaymentPort.UpdateKKTPeriod(NabuPdfGenerator.Payment.UpdateKKTPeriodRequest1 request) {
            return base.Channel.UpdateKKTPeriod(request);
        }
        
        public NabuPdfGenerator.Payment.UpdateKKTPeriodResponse UpdateKKTPeriod(NabuPdfGenerator.Payment.UpdateKKTPeriodRequest UpdateKKTPeriodRequest) {
            NabuPdfGenerator.Payment.UpdateKKTPeriodRequest1 inValue = new NabuPdfGenerator.Payment.UpdateKKTPeriodRequest1();
            inValue.UpdateKKTPeriodRequest = UpdateKKTPeriodRequest;
            NabuPdfGenerator.Payment.UpdateKKTPeriodResponse1 retVal = ((NabuPdfGenerator.Payment.PaymentPort)(this)).UpdateKKTPeriod(inValue);
            return retVal.UpdateKKTPeriodResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NabuPdfGenerator.Payment.UpdateKKTPeriodResponse1> NabuPdfGenerator.Payment.PaymentPort.UpdateKKTPeriodAsync(NabuPdfGenerator.Payment.UpdateKKTPeriodRequest1 request) {
            return base.Channel.UpdateKKTPeriodAsync(request);
        }
        
        public System.Threading.Tasks.Task<NabuPdfGenerator.Payment.UpdateKKTPeriodResponse1> UpdateKKTPeriodAsync(NabuPdfGenerator.Payment.UpdateKKTPeriodRequest UpdateKKTPeriodRequest) {
            NabuPdfGenerator.Payment.UpdateKKTPeriodRequest1 inValue = new NabuPdfGenerator.Payment.UpdateKKTPeriodRequest1();
            inValue.UpdateKKTPeriodRequest = UpdateKKTPeriodRequest;
            return ((NabuPdfGenerator.Payment.PaymentPort)(this)).UpdateKKTPeriodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NabuPdfGenerator.Payment.KKTStatusResponse1 NabuPdfGenerator.Payment.PaymentPort.KKTStatus(NabuPdfGenerator.Payment.KKTStatusRequest1 request) {
            return base.Channel.KKTStatus(request);
        }
        
        public NabuPdfGenerator.Payment.KKTStatusResponse KKTStatus(NabuPdfGenerator.Payment.KKTStatusRequest KKTStatusRequest) {
            NabuPdfGenerator.Payment.KKTStatusRequest1 inValue = new NabuPdfGenerator.Payment.KKTStatusRequest1();
            inValue.KKTStatusRequest = KKTStatusRequest;
            NabuPdfGenerator.Payment.KKTStatusResponse1 retVal = ((NabuPdfGenerator.Payment.PaymentPort)(this)).KKTStatus(inValue);
            return retVal.KKTStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NabuPdfGenerator.Payment.KKTStatusResponse1> NabuPdfGenerator.Payment.PaymentPort.KKTStatusAsync(NabuPdfGenerator.Payment.KKTStatusRequest1 request) {
            return base.Channel.KKTStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<NabuPdfGenerator.Payment.KKTStatusResponse1> KKTStatusAsync(NabuPdfGenerator.Payment.KKTStatusRequest KKTStatusRequest) {
            NabuPdfGenerator.Payment.KKTStatusRequest1 inValue = new NabuPdfGenerator.Payment.KKTStatusRequest1();
            inValue.KKTStatusRequest = KKTStatusRequest;
            return ((NabuPdfGenerator.Payment.PaymentPort)(this)).KKTStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NabuPdfGenerator.Payment.paymentResponse1 NabuPdfGenerator.Payment.PaymentPort.payment(NabuPdfGenerator.Payment.paymentRequest1 request) {
            return base.Channel.payment(request);
        }
        
        public NabuPdfGenerator.Payment.paymentResponse payment(NabuPdfGenerator.Payment.paymentRequest paymentRequest) {
            NabuPdfGenerator.Payment.paymentRequest1 inValue = new NabuPdfGenerator.Payment.paymentRequest1();
            inValue.paymentRequest = paymentRequest;
            NabuPdfGenerator.Payment.paymentResponse1 retVal = ((NabuPdfGenerator.Payment.PaymentPort)(this)).payment(inValue);
            return retVal.paymentResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NabuPdfGenerator.Payment.paymentResponse1> NabuPdfGenerator.Payment.PaymentPort.paymentAsync(NabuPdfGenerator.Payment.paymentRequest1 request) {
            return base.Channel.paymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<NabuPdfGenerator.Payment.paymentResponse1> paymentAsync(NabuPdfGenerator.Payment.paymentRequest paymentRequest) {
            NabuPdfGenerator.Payment.paymentRequest1 inValue = new NabuPdfGenerator.Payment.paymentRequest1();
            inValue.paymentRequest = paymentRequest;
            return ((NabuPdfGenerator.Payment.PaymentPort)(this)).paymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NabuPdfGenerator.Payment.afterPaymentAccountResponse1 NabuPdfGenerator.Payment.PaymentPort.afterPaymentAccount(NabuPdfGenerator.Payment.afterPaymentAccountRequest1 request) {
            return base.Channel.afterPaymentAccount(request);
        }
        
        public NabuPdfGenerator.Payment.afterPaymentAccountResponse afterPaymentAccount(NabuPdfGenerator.Payment.afterPaymentAccountRequest afterPaymentAccountRequest) {
            NabuPdfGenerator.Payment.afterPaymentAccountRequest1 inValue = new NabuPdfGenerator.Payment.afterPaymentAccountRequest1();
            inValue.afterPaymentAccountRequest = afterPaymentAccountRequest;
            NabuPdfGenerator.Payment.afterPaymentAccountResponse1 retVal = ((NabuPdfGenerator.Payment.PaymentPort)(this)).afterPaymentAccount(inValue);
            return retVal.afterPaymentAccountResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NabuPdfGenerator.Payment.afterPaymentAccountResponse1> NabuPdfGenerator.Payment.PaymentPort.afterPaymentAccountAsync(NabuPdfGenerator.Payment.afterPaymentAccountRequest1 request) {
            return base.Channel.afterPaymentAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<NabuPdfGenerator.Payment.afterPaymentAccountResponse1> afterPaymentAccountAsync(NabuPdfGenerator.Payment.afterPaymentAccountRequest afterPaymentAccountRequest) {
            NabuPdfGenerator.Payment.afterPaymentAccountRequest1 inValue = new NabuPdfGenerator.Payment.afterPaymentAccountRequest1();
            inValue.afterPaymentAccountRequest = afterPaymentAccountRequest;
            return ((NabuPdfGenerator.Payment.PaymentPort)(this)).afterPaymentAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NabuPdfGenerator.Payment.documentResponse1 NabuPdfGenerator.Payment.PaymentPort.document(NabuPdfGenerator.Payment.documentRequest1 request) {
            return base.Channel.document(request);
        }
        
        public NabuPdfGenerator.Payment.documentResponse document(NabuPdfGenerator.Payment.documentRequest documentRequest) {
            NabuPdfGenerator.Payment.documentRequest1 inValue = new NabuPdfGenerator.Payment.documentRequest1();
            inValue.documentRequest = documentRequest;
            NabuPdfGenerator.Payment.documentResponse1 retVal = ((NabuPdfGenerator.Payment.PaymentPort)(this)).document(inValue);
            return retVal.documentResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NabuPdfGenerator.Payment.documentResponse1> NabuPdfGenerator.Payment.PaymentPort.documentAsync(NabuPdfGenerator.Payment.documentRequest1 request) {
            return base.Channel.documentAsync(request);
        }
        
        public System.Threading.Tasks.Task<NabuPdfGenerator.Payment.documentResponse1> documentAsync(NabuPdfGenerator.Payment.documentRequest documentRequest) {
            NabuPdfGenerator.Payment.documentRequest1 inValue = new NabuPdfGenerator.Payment.documentRequest1();
            inValue.documentRequest = documentRequest;
            return ((NabuPdfGenerator.Payment.PaymentPort)(this)).documentAsync(inValue);
        }
    }
}
